### ISSUE TITLE
Model Assumptions

### ISSUE THREAD

**Issue by cshjin** [cshjin/Microgrid_sim#1]
Describe all the possible assumptions we need literally.

**Comment by jinhw1989** [comment]
Assumptions in thesis:
* Only consider electric energy, and ignore thermal energy; :heavy_check_mark: 
* Distribution grid has sufficient energy support if needed; :heavy_check_mark: 
* Consider single Microgrid, ignoring the cooperative structure of multi-Microgrid; :heavy_check_mark: 
* Consider a fixed amount of generators, rather than adding more generators into single Microgrid; :heavy_check_mark: 
* Ignore the cost of switching operation mode from grid-tile to island, vice versa; 
* Ignore the line capacity;
* Microgrid has some common sources, which are used by all the members in the community;
* Microgrid has batteries to store energy, which can be shared by the consumers as needed;
* In our model, we consider three types of time-of-use (TOU), rather than varies by hours.
* Ignore the installation and maintenance cost of micro sources, such as batteries, solar panels, and windmills;
* Ignore the energy loss inside Microgrid, such as transmission energy reduction; :question: 

Some other options:
* Grid can get energy from Microgrid or consumers;
* Microgrid can get energy from its own common sources, and also from grid or consumers;
* Consumers can get energy from its private sources, and also from grid, batteries in Microgrid or common sources in Microgrid;
* Microgrid has distributed micro sources, such as windmill, solar panel such that energy can be distributed between nodes(in the first step, ignore the fairness between those consumers, that is to say, the sell price of consumers will not take into account);
* Not take materials of all kind of renewable energy resources into account;
* Consumers in MG cannot direct sell energy to G, they can store their energy to batteries and MG decide whether to sell or not(to be removed later version); 
* Consider short-term optimization, rather than a long-term one;

**Comment by cshjin** [comment]
No update for a long time, close for now.
